### ISSUE TITLE
Gluster Prometheus should also provide brick level IOPS on from Interval Stats

### ISSUE THREAD

**Issue by anmolsachan** [gluster/gluster-prometheus#101]
Currently GP provides ` gluster_volume_profile_total_writes`, `gluster_volume_profile_total_reads`, `gluster_volume_profile_duration_secs` which are cumulative stats. These cannot be used to calculate the IOPS for a brick or a volume. GP should provide calculated brick level iops based on the refresh interval of GP.

**Comment by labazza** [comment]
i get these metrics from[ disk_io telegraf exporter](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/diskio)

**Comment by shtripat** [comment]
@anmolsachan I agree. We will have to capture block-wise reads/writes details from `profile info` from `IntervalStats` and use the formula `((total reads + total writes) across all the blocks / duration)`.

This would becomes iops for brick level and then at volume level it would be aggregated.

The metrics exposed would be `gluster_brick_iops` with labels `volume, brick`

@aravindavk @JohnStrunk comments?

**Comment by JohnStrunk** [comment]
Rates are much more useful than cumulative for the admin. But I am rather leery of directly exporting a rate as it tends to be difficult to do correctly.

Isn't there a way to get Prometheus to convert a cumulative into a rate? Most monitoring software I've dealt with recommend doing it that way. (data is provided as cumulative/counter and the reporting software turns it into a rate/gauge.

Converting brick-level to volume-level... What sort of aggregation would we use here? Potentially this could end up being different for reads vs. writes. Reads get spread across replicas, so summing makes sense. A write goes to all replicas, so would we still want to sum those or does average or max make more sense?

My only other comment would be that brick iops is not the same as device iops. We need to have device-level at least as much as we need brick-level. In environments like AWS, devices have a clear max iops that we should be able to validate against.

**Comment by shtripat** [comment]
>> Rates are much more useful than cumulative for the admin. But I am rather leery of directly exporting a rate >> as it tends to be difficult to do correctly.

@JohnStrunk so in tendrl we used to sum all the reads and writes across blocks and divide by duration to get iops value at brick level as metrics. Regarding disk level here in this case disk specific metrics are alrady exposed by k8s so we are not doing that.

>> Converting brick-level to volume-level... What sort of aggregation would we use here?
To calculate volume level IOPS values we use formula `alias(sumSeries(tendrl.names.$cluster_id.volumes.$volume_name.nodes.*.bricks.*.iops.*), '$volume_name')` in grafana in case of tendrl

>> My only other comment would be that brick iops is not the same as device iops.
That's correct. Brick level iops we would collect as part pf gluster-prometheus and k8s already captures device specific metrics and the same could be used for deriving iops at device level

Based on this, should we go ahead and start collecting metric `gluster_brick_iops` as suggested originally on the issue?

**Comment by anmolsachan** [comment]
I agree with points mentioned by @shtripat above. I raised this issue get metrics for Volume level Gluster dashboard which needs to show the Volume and brick specific metrics in a gluster cluster.
The device level IOPS can go into the node specific dashboard of k8s if required.

>> A write goes to all replicas, so would we still want to sum those or does average or max make more sense?

The above point by @JohnStrunk makes sense to me and should be discussed here. 
If we take up a scenario of two volumes, 2*3 and 3*4 Distributed-replicated volumes; If same data is now written to both volumes, max and average will give similar or close values for both which might not be correct. When is comes to sum, it makes more sense to me.

**Comment by onnorom** [comment]
Hi, 
I am wondering if there's anything i may be missing that need to be enabled in order for me to get gluster_volume_profile_* measurements? I have set the necessary collectors in the /etc/gluster-exporter/gluster-exporter.toml files as below:

[collectors.gluster_volume_profile]
name = "gluster_volume_profile"
sync-interval = 5
disabled = false

[collectors.gluster_volume_counts]
name = "gluster_volume_counts"
sync-interval = 5
disabled = false

[collectors.gluster_volume_heal]
name = "gluster_volume_heal"
sync-interval = 5
disabled = false

However, i don't see any measurement collected with that name.

I do see the following measurements:

gluster_brick_capacity_bytes_total
gluster_brick_capacity_free_bytes
gluster_brick_capacity_used_bytes
gluster_brick_inodes_free
gluster_brick_inodes_total
gluster_brick_inodes_used
gluster_brick_lv_metadata_percent
gluster_brick_lv_metadata_size_bytes
gluster_brick_lv_percent
gluster_brick_lv_size_bytes
gluster_brick_up
gluster_cpu_percentage
gluster_elapsed_time_seconds
gluster_memory_percentage
gluster_process:gluster_cpu_percentage:avg1h
gluster_process:gluster_elapsed_time_seconds:rate5m
gluster_process:gluster_memory_percentage:avg1h
gluster_resident_memory_bytes
gluster_subvol_capacity_total_bytes
gluster_subvol_capacity_used_bytes
gluster_vg_extent_alloc_count
gluster_vg_extent_total_count
gluster_virtual_memory_bytes
gluster_volume_heal_count
gluster_volume_split_brain_heal_count
