### ISSUE TITLE
glusterd1 and glusterd2 compatibility

### ISSUE THREAD

**Issue by aravindavk** [gluster/gluster-prometheus#12]
Gluster Prometheus exporter should be compatible with glusterd1 and
glusterd2 whenever it is possible.

Below flags to exporter will help to identify the management daemon
used.

```
--gluster-mgmt=<name>  (Choices: glusterd1, glusterd2. Default is "glusterd1")
--glusterd-dir=<path> (Default is `/var/lib/glusterd2` in case of
    glusterd2 else `/var/lib/glusterd`)
```

## Plan

Metrics collectors should not run gluster cli or REST api calls. They
all consume input json files and export the metrics or collects the
additional details and exports it.

Example - Number of Volumes: A separate thread which runs `gluster
volume info --xml` if configured to use glusterd1 else calls REST API
`GET http://localhost:24007/v1/volumes`. Both will generate the output
json in the same format which will be understood by metrics collector
thread. Metrics collector thread need not check the data coming from
`glusterd1` or `glusterd2`.

Example - Brick utilization: Volume info json collected as above,
metrics collector will look into the volinfo.json and collects the
utilization details and exports the details.

Example - Volume Profile: Compatibility thread will run CLI and
consume xml in case of glusterd1, runs REST API in case of
glusterd2.

## Support of enable/disable of Metrics

All exported metrics should expose configuration via CLI or config to
enable/disable. For example, `--utilization-metrics=enabled`. This
will give more control for choosing the metrics which are compatible
for the target deployment.

## Auto disable Metrics collection if not compatible

If a metric is not supported with `glusterd1`, that should be
automatically disabled based on the flag `--gluster-mgmt=glusterd2`

**Comment by shtripat** [comment]
@aravindavk 
> All exported metrics should expose configuration via CLI or config to enable/disable.

I am working on a PR to come up with a configuration which would help setting enable/disable flag and sync interval for individual collectors. A sample conf file would look as below

```
[
        {
                "name": "metric_ps",
                "sync_interval": 5,
                "enabled": true
        },
        {
                "name": "metric_brick",
                "sync_interval": 5,
                "enabled": true
        }
]
```

**Comment by aravindavk** [comment]
With the following PRs, both Glusterd1 and Glusterd2 are supported, all future features will support both.

- Configuration PRs #24 and #49
- Volinfo compatible with GD1 and GD2 #35
- Getting Local Peer ID #33

Closing this issue.
