### ISSUE TITLE
Not all metrics are available

### ISSUE THREAD

**Issue by khalid151** [gluster/gluster-prometheus#148]
Hi,
I have `gluster-exporter` running on multiple nodes\peers. On the first node, all metrics are available and working as expected but on others, some of the metrics are missing.

For example, `gluster_brick_up` shows up on the first node but doesn't on the second or third one.

The exporter and glusterd versions:
```
$ gluster-exporter -version
version   : v0.3-dev.73.git4baab01
go version: go1.11.5
go OS/arch: linux/amd64

$ glusterd -V
glusterfs 4.1.8
...
```

**Comment by aravindavk** [comment]
Some metrics are cluster level metrics, if we export from all exporters then that will be duplicate records in Prometheus server. So first up peer in peer list will export these metrics.

**Comment by khalid151** [comment]
Okay, I was only checking "/metrics" of each individual exporter.
After adding these to Prometheus, things work as expected.
Thank you.
