### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by davisj** [gluster/gluster-prometheus#166]
Greetings, 

I'm wondering if there are any plans to make a binary release of the exporter public?
I ask as I was unable to configure a Golang development environment with the necessary libraries on a CentOS 7 workstation.

**Comment by aravindavk** [comment]
Sorry for the inconvenience. I will plan for the binary release.

**Comment by aravindavk** [comment]
Nightly RPMs are available here for CentOS 7 http://artifacts.ci.centos.org/gluster/gluster-prometheus-nightly/

**Comment by davisj** [comment]
That is terrific. Thank you very much!

**Comment by davisj** [comment]
works for me
