### ISSUE TITLE
gluster_brick_* metrics have incorrect topology

### ISSUE THREAD

**Issue by irischad** [gluster/gluster-prometheus#168]
In a distributed replica setup, gluster-exporter has an incorrect/inconsistent view of the disk topology. 

The actual topology is:

`Type: Distributed-Replicate`
`Volume ID: 6db232a9-e7a1-46ab-bca4-bc69cf5cb68e`
`Status: Started`
`Snapshot Count: 0`
`Number of Bricks: 3 x 2 = 6`
`Transport-type: tcp`
`Bricks:`
`Brick1: gluster00:/export/brick0/srv`
`Brick2: gluster01:/export/brick0/srv`
`Brick3: gluster00:/export/brick1/srv`
`Brick4: gluster01:/export/brick1/srv`
`Brick5: gluster00:/export/brick2/srv`
`Brick6: gluster01:/export/brick2/srv`

Yet the pairing shown by:
`curl localhost:8080/metrics | grep gluster_brick_`
is different (see attached output from node1 and node2).  Additionally, note that node2 has extra output, including the metric `gluster_brick_up` (not present in the output on node1) which does have the correct brick topology, interestingly enough.

Additional information:
- CentOS 7
- glusterfs 6.5. # Issue was present in 6.4 too

`# /usr/sbin/gluster-exporter --version`
`version   : v0.3-dev.86.git9eacc41`
`go version: go1.11.5`
`go OS/arch: linux/amd64`

[node1_gluster_brick_.txt](https://github.com/gluster/gluster-prometheus/files/3498780/node1_gluster_brick_.txt)
[node2_gluster_brick_.txt](https://github.com/gluster/gluster-prometheus/files/3498781/node2_gluster_brick_.txt)

**Comment by irischad** [comment]
I have a test cluster in a 4 x 2 = 8 configuration, I just installed the gluster-exporter there and am seeing similar issues:

`Volume Name: gv0`
`Type: Distributed-Replicate`
`Volume ID: 0243125e-9b5b-4c46-a98d-f4610a570c8f`
`Status: Started`
`Snapshot Count: 0`
`Number of Bricks: 4 x 2 = 8`
`Transport-type: tcp`
`Bricks:`
`Brick1: gluster0:/export/brick0/srv`
`Brick2: gluster1:/export/brick0/srv`
`Brick3: gluster0:/export/brick1/srv`
`Brick4: gluster1:/export/brick1/srv`
`Brick5: gluster0:/export/brick2/srv`
`Brick6: gluster1:/export/brick2/srv`
`Brick7: gluster0:/export/brick3/srv`
`Brick8: gluster1:/export/brick3/srv`

The output of
`curl localhost:8080/metrics | grep gluster_brick_`
is attached, and again we see the mismatch, and again the `gluster_brick_up` metric on the second node only.

Additional information:
- CentOS  7
- GlusterFS 6.4

`# gluster-exporter --version`
`version   : v0.3-dev.87.git04465af`
`go version: go1.11.5`
`go OS/arch: linux/amd64`

**Comment by aravindavk** [comment]
Looks like the wrong path is added in the output of `gluster_brick_capacity_*` and `gluster_brick_inode*` metrics. I will look into the issue. 

`gluster_brick_up` is cluster-level metrics, which will be exported only from one of the nodes in Cluster. Exported data will have metrics of all bricks.

**Comment by irischad** [comment]
This fix looks good - thanks for fixing it!
