### ISSUE TITLE
glusterfs inside openshift monitoring

### ISSUE THREAD

**Issue by bortek** [gluster/gluster-prometheus#17]
Sorry for creating an issue but I was not sure where ti place a question.

I am using glusterfs storage inside opensshift, it runs as pods and provides storage to to other pods/apps in the openshift cluster.  

I assume that gluster-prometheus is designed to be running on the same host where gluster is running. But how can I use it to scrape data from the pods in the openshift, if that is at all possible?

Are there any metrics available to monitor gluster heal status and peer status?

Thanks!

**Comment by aravindavk** [comment]
Thanks for opening the issue. We are still working on the deployment part and a few other metrics

- Metrics which needs to be collected from the same pod where bricks or gluster process are running.(For example: Process related metrics)
- Metrics which can be collected by running as different pod but should be run on same node where bricks are running(For example: Bricks utilization assuming this separate pod can access the same devices)
- Metrics which can be collected by spawning pod in anywhere in the cluster (Example: Cluster metrics which can be gathered by querying gluster cli or REST apis)

> Are there any metrics available to monitor gluster heal status and peer status?

In progress, we will update you once these metrics will be available.

**Comment by JohnStrunk** [comment]
@aravindavk Do you see any problems with having a gluster-prometheus container as a part of the gluster pods? This would enable decoupling while also providing the co-location necessary to access the resources for monitoring.

**Comment by aravindavk** [comment]
> @aravindavk Do you see any problems with having a gluster-prometheus container as a part of the gluster pods? This would enable decoupling while also providing the co-location necessary to access the resources for monitoring.

No problems for most of the metrics. But for cluster level metrics, exporting from all nodes/pods results in duplicate data in Prometheus(Unless one exporter in cluster identifies itself as leader and exports cluster data). 

We can delegate leader election to kubernetes if we separate the cluster level metrics exporter as separate pod, which can talk to any one glusterd and collect cluster metrics.

**Comment by JohnStrunk** [comment]
I'd like to get a solid plan for this (assuming we don't already have it and just need to document it). We need to be opinionated on how this should be configured/deployed w/ GCS.

It sounds like we're going to end up w/ a sidecar for node info and a Deployment/pod for the cluster as a whole. This has implications for the operator, so getting it all written down is important.

(also ref #3)
