### ISSUE TITLE
Explain the deployment architecture for gluster prometheus

### ISSUE THREAD

**Issue by shtripat** [gluster/gluster-prometheus#28]
We need to document how the gluster-prometheus works and how it fits and gets consumed in overall gluster eco-system or GCS (Gluster Container Storage) eco system.

**Comment by JohnStrunk** [comment]
Potentially a dup of #27?
Related to: #27 #17 #3
Also, @pranithk says there's a dependency on figuring out #12

**Comment by aravindavk** [comment]
Closing this issue based on previous comment
