### ISSUE TITLE
Get Local PeerID

### ISSUE THREAD

**Issue by DrEVILish** [gluster/gluster-prometheus#31]
Can pull peerID automatically either by

$ gluster pool list | awk '/localhost/ {print $1}'
or
$ cat /var/lib/glusterd/glusterd.info which stores the Local Peers UUID

The second seems a better option because a go script can read the file.

```
parts := strings.Split(gdInfo, "=")
parts[1]
```
Should return the UUID

**Comment by aravindavk** [comment]
This need to be handled to work with both glusterd1 and glusterd2.

    if exists(args.glusterd_workdir + "/uuid.toml") {
        localPeerID = parse_toml(args.glusterd_workdir + "/uuid.toml")
    } else {
        localPeerID = parse_info(args.glusterd_workdir + "/glusterd.info")
    }

`glusterd-workdir` can be accepted as parameter.

**Comment by DrEVILish** [comment]
Code implemented.
