### ISSUE TITLE
Number of volumes

### ISSUE THREAD

**Issue by nixpanic** [gluster/gluster-prometheus#5]
It would be useful to have the number of volumes provided as well. With this users can see if there are any kubernetes/openshift jobs requesting many volumes at a certain time.

**Comment by shtripat** [comment]
No of volumes is more cluster level metric. In additional below would be useful metrics
- no of bricks
- no of gluster pods (no of peers)
- cluster overall status (healthy/unhealthy)
- status wise split of volumes (e.g. UP 2, DOWN 3)
- status wise split of bricks (e.g. Started 2, Stopped 1)
- device count
- overall capacity and utilization

**Comment by labazza** [comment]
i think this can be achieved from prometheus recording rules using count_over_time()

**Comment by shtripat** [comment]
> No of volumes is more cluster level metric. In additional below would be useful metrics
> 
>     * no of bricks

Done

> 
>     * no of gluster pods (no of peers)

Will be taken care by k8s

> 
>     * cluster overall status (healthy/unhealthy)

Operator to tackle this as operator itself needs to be monitored and should have some metrics exposed. Cluster overall health is ideal candidate for this.

> 
>     * status wise split of volumes (e.g. UP 2, DOWN 3)

A metric `gluster_volume_up` exposed and recording rules could be used for total no of up/down volumes required.

> 
>     * status wise split of bricks (e.g. Started 2, Stopped 1)

A metric `gluster_brick_up` exposed and recording rule could be used for total no of up/down bricks if required.

> 
>     * device count

k8s exposes the device specific metrics and recording rules could be used for getting the overall count

> 
>     * overall capacity and utilization

Done.

Based on above comment, I am closing this issue. Kindly raise separate ones on need basis.
