### ISSUE TITLE
Export Self-Heal  related metrics

### ISSUE THREAD

**Issue by aravindavk** [gluster/gluster-prometheus#53]
Add support for exporter to export Self-Heal related metrics compatible to both Glusterd1 and Glusterd2.

**Comment by aravindavk** [comment]
Assigning to @vredara since this is being worked on with PR #39

**Comment by atinmu** [comment]
@vredara Any progress on this? Please note GCS/0.3 release is tomorrow.

**Comment by vredara** [comment]
PR  #64 addressed interface part of this. today will add code to export heal metrics.

**Comment by vredara** [comment]
we can move this GCS 0.4 . heal should be exported only from masters. I have to do some tests on this.

**Comment by vredara** [comment]
PR #75 has the checkin for this. I exported heal count. once it is merged, we are ready for GCS 0.3

**Comment by aravindavk** [comment]
PR #75 is merged now. Closing this issue.
