### ISSUE TITLE
Export Volume Profile Metrics

### ISSUE THREAD

**Issue by aravindavk** [gluster/gluster-prometheus#55]
Add support for collecting and exporting Volume profile metrics compatible to Glusterd1 and Glusterd2

**Comment by shtripat** [comment]
@aravindavk I feel this is different from https://github.com/gluster/gluster-prometheus/pull/15 provided metrics.
Do we need to introduce another info json for profile data for this?

**Comment by aravindavk** [comment]
This issue for getting volume profile output from `gluster volume <volname> profile info cumulative --xml` in case of glusterd1 and profile API call in Glusterd2(Not yet available in Glusterd2, PR under review: https://github.com/gluster/glusterd2/pull/962)

**Comment by shtripat** [comment]
>> This issue for getting volume profile output from gluster volume <volname> profile info cumulative --xml >> in case of glusterd1 and profile API call in Glusterd2(Not yet available in Glusterd2, PR under review:
>> gluster/glusterd2#962)

@aravindavk I feel we need to report duration, total read and total writes brickwise here. Based on this IOPS could be derived. Right?
