### ISSUE TITLE
Dependancy isn't cross arch compatibility

### ISSUE THREAD

**Issue by DrEVILish** [gluster/gluster-prometheus#56]
While trying to perform an install of the latest software, I get an error:

Odroid HC2 - Armbian - Ubuntu 18.04.1 LTS - 4.14.69-odroidxu4
go version go1.10.1 linux/arm

```
Go1.9 or later is available on the system.

dep package is missing on the system
gometalinter package is missing on the system
Makefile:61: recipe for target 'check-reqs' failed
make: *** [check-reqs] Error 1
```

gometalinter isn't released for arm32 or arm64 so has to be installed from source at build time.

**Comment by DrEVILish** [comment]
As part of the make process detect if are missing and if GO is installed install the required dependancies.

go get -u github.com/golang/dep/cmd/dep
go get github.com/alecthomas/gometalinter
gometalinter --install --update

**Comment by aravindavk** [comment]
Try running `scripts/install-reqs.sh`, I will update the doc accordingly.
