### ISSUE TITLE
List of metrics from WA perspective

### ISSUE THREAD

**Issue by shtripat** [gluster/gluster-prometheus#8]
Created this list as one place where all the required metrics from WA perspective are captured. These might be overlapped with other issues already listed

- Cluster Level
-- Overall Status (healthy/unhealthy)
-- No of snapshots
-- No if peers
-- No of volumes
-- No of bricks
-- geo-rep session (state wise breakup)
-- no of client connections
-- Overall IOPS
-- Overall capacity utilization
-- Capacity Available
-- Weekly growth rate
-- weeks pending
-- Throughput
-- Volume status wise breakup
-- Host (peer) status wise breakup
-- Brick status wise breakup

- Volume Level
-- State
-- Bricks (status wise breakup)
-- No of bricks
-- geo-rep sessions (state wise breakup)
-- rebalance counters
-- rebalance status
-- no of snapshots
-- capacity utilization
-- capacity available
-- weekly growth rate
-- weeks pending
-- IOPS
-- LVM utilization (metadata and data)
-- profiling info (e.g. fop for locks, read-write, inode operations, entry operations)

- Brick Level
-- status
-- capacity utilization
-- capacity available
-- weekly growth rate
-- weeks pending
-- heal information
-- IOPS
-- LVM usage (metadata and data)
-- throughput
-- latency
-- mount point utilization

- Host/Peer Level
-- Status (connected/disconnected)
-- no of bricks
-- bricks status wise breakup
-- memory available
-- memory utilization
-- swap free
-- swap utilization
-- CPU utilization
-- network throughput
-- dropped packets per sec
-- errors per sec

**Comment by sabose** [comment]
Closing this as we're no longer targeting WA requirements
