### ISSUE TITLE
Define the hierarchy of metrics to be mainatained in prometheus

### ISSUE THREAD

**Issue by shtripat** [gluster/gluster-prometheus#9]
We need to define the hierarchical structure of metrics which would be maintained with prometheus. A sample structure could be something like

`clusters/{cluster-id}/{cluster-specific-metrics like cluster health, no of connections etc}`
`clusters/{cluster-id}/volumes/{volume-id}/{volume-specific-metrics like no of bricks, status etc}`
`clusters/{cluster-id}/volumes/{volume-id}/bricks/{brick-id/brick-name}/{brick-specific-metrics like utilization etc}`

**Comment by aravindavk** [comment]
Prometheus metrics uses labels and no hierarchical structure used, all the required details will be available as labels. Please add more details to this requirement.

**Comment by shtripat** [comment]
@aravindavk agree.
May be we would need to use a mix of metrics names and labels.
I can think of metric names something like

`cluster_{cluster-id}_{metric-name}`
`cluster_{cluster-id}_volume_{volume-id}_{metric-name}`
`cluster_{cluster-id}_volume_{volume-id}_brick_{brick-id}_{metric-name}`

We would need to make sure individual metric names say volume's utilization should not contain character `_` and in case more detailing required, we should use labels.

What you suggest?

**Comment by aravindavk** [comment]
Each metric name should be same for all clusters or volumes. `<metric-name>{cluster-id=<cluster-id>,...}`. Without this ploting generalized charts is difficult. All these labels in Prometheus can be used as filters or grouping.

For example:

    gluster_number_of_volumes{cluster-id="3793bda0-7f04-4de5-a449-86ebcb197f0f"} = 10
    gluster_volume_utilization{cluster-id="3793bda0-7f04-4de5-a449-86ebcb197f0f",volume="gv1", volume-id="747b86a7-6c28-46e0-b5de-34d5ab5d3ccf"} = 1000000
    gluster_brick_memory{cluster-id="3793bda0-7f04-4de5-a449-86ebcb197f0f",volume="gv1", volume-id="747b86a7-6c28-46e0-b5de-34d5ab5d3ccf", brick-host="node1.example.com", brick-path="/exports/bricks/gv1/brick1/brick"} = 356

**Comment by shtripat** [comment]
@aravindavk ack. thanks for clarifying.
I am fine with the approach.
