### ISSUE TITLE
Enable the Volume profile if profile collector is enabled

### ISSUE THREAD

**Issue by shtripat** [gluster/gluster-prometheus#90]
This is required to make sure if profiling related metrics needs to be collected, profiling should be enabled for the volumes.

**Comment by shtripat** [comment]
@aravindavk if the profile info collector is enabled, should we enable profiling for all the volumes in the underlying cluster? Is it something which should be done under the cover by collectors?

Suggestions @JohnStrunk @sidharthanup @atinmu

**Comment by shtripat** [comment]
@JohnStrunk so if I understand correct, you mean to keep profiling enabled always for all the volumes. Or still we should enable for all the volumes based on collector enabled?

**Comment by aravindavk** [comment]
If volume profile collector is enabled in gluster-exporter, then this option needs to be enabled for all Volumes. But if profiling is disabled for a Volume by user then we should be careful not to enable it again.(This is still unknown, how to achieve this without storing any state in Prometheus. One posibility is to check volinfo.Options, if profile option is off then don't enable. But if user reset the profile option then this will not be available in volinfo.Options).

**Comment by shtripat** [comment]
So what I understand here, it should be like if profile info collector is enabled we should check if profiling is enabled for volume. If its enabled for a volume, then only expose metrics for that volume. If it disabled explicitly for a volume, we wont expose metrics for those volumes.

Is this understanding correct?
@aravindavk @JohnStrunk ^^^

**Comment by aravindavk** [comment]
> So what I understand here, it should be like if profile info collector is enabled we should check if profiling is enabled for volume. If its enabled for a volume, then only expose metrics for that volume. If it disabled explicitly for a volume, we wont expose metrics for those volumes.

- When exporter starts, we can check if collector is enabled then get volume info and enable volume profile if not enabled and if not explicitly disabled.
```
func enableProfile(volume) {
    _, exists := volinfo.Options[ProfileKey]
    if !exists {
         profileEnable(volume)
    }
}
```

- In the collector function, collect and export metrics only if Profile is enabled.

**Comment by shtripat** [comment]
@aravindavk based on https://github.com/gluster/gluster-prometheus/issues/90#issuecomment-446067856 from @JohnStrunk shouldn't we enable profiling for all the volumes in case collector is enabled. Anyway this collector would run only from leader node.

**Comment by JohnStrunk** [comment]
My original coment was that if we start the collector, we should also turn on profile data for all volumes.
@aravindavk added to this by stating that if an admin has specifically disabled profiling for a volume, we shouldn't enable it.

I don't know how this works in the gd2 world, but w/ gd1, you could `gluster vol info` and see all the options that had been specifically set, even if they were set back to their default value.
So, an on/off option "foo" could be in 3 states:
- default (nothing printed in g v info)
- on (admin did g v set foo on; shown in g v info)
- off (admin did g v set foo off; shown in g v info)
To return a value to default requires g v reset foo, and it'll no longer appear in g v info.

The idea is to keep this existing distinction between "default" (we should enable profiling when we load the collector) and "off" (the admin actually turned it off at some point, so we shouldn't adjust it).

**Comment by shtripat** [comment]
@aravindavk is this behavior same with gd2 as well? At least based on comment https://github.com/gluster/gluster-prometheus/issues/90#issuecomment-447775895, it doesnt look like. Do we need some fix/changes in gd2 for this?

**Comment by aravindavk** [comment]
> @aravindavk so I created a fresh volume and by default the options io-stats.latency-measurement and io-stats.count-fop-hits are set as off. Now with this how do we make out if explicitly profiling is disabled for the volumes or its not enabled at all. Looks these options get set by default for the all the volumes newly getting created.

I am not seeing those options enabled in freshly create volume in Gd2, an you check again?

```
[root@fedora28 ~]# glustercli volume create gv1 fedora28.example.com:/bricks/gv1/b1 --force
gv1 Volume created successfully
Volume ID:  f4eb57d6-2fc7-45ee-812e-800182a63f55
[root@fedora28 ~]#
[root@fedora28 ~]# glustercli volume info

Volume Name: gv1
Type: Distribute
Volume ID: f4eb57d6-2fc7-45ee-812e-800182a63f55
State: Created
Transport-type: tcp
Options:
    performance/io-cache.io-cache: off
    performance/md-cache.md-cache: off
    performance/open-behind.open-behind: off
    performance/quick-read.quick-read: off
    performance/read-ahead.read-ahead: off
    performance/readdir-ahead.readdir-ahead: off
    performance/write-behind.write-behind: off
Number of Bricks: 1
Brick1: fedora28.example.com:/bricks/gv1/b1
```
Even ReST API response doesn't show these options( `curl http://localhost:24007/v1/volumes`)

```json
        "name": "gv1",
        "options": {
            "performance/io-cache.io-cache": "off",
            "performance/md-cache.md-cache": "off",
            "performance/open-behind.open-behind": "off",
            "performance/quick-read.quick-read": "off",
            "performance/read-ahead.read-ahead": "off",
            "performance/readdir-ahead.readdir-ahead": "off",
            "performance/write-behind.write-behind": "off"
        },
```
